name: Build and Release
permissions:
  contents: write
on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Superior Unix-like systems first 🐧
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            artifact_name: kitty-pane-bg
            asset_name: kitty-pane-bg-linux-x86_64
          # Windows support (because someone has to help the lost souls) 🪟
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: kitty-pane-bg.exe
            asset_name: kitty-pane-bg-windows-x86_64.exe

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Test
      if: matrix.target == 'x86_64-unknown-linux-gnu'
      run: cargo test --target ${{ matrix.target }}

    - name: Rename binary for release
      run: |
        mkdir -p dist
        cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} dist/${{ matrix.asset_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: dist/${{ matrix.asset_name }}

  release:
    name: Create Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          kitty-pane-bg-linux-x86_64/kitty-pane-bg-linux-x86_64
          kitty-pane-bg-windows-x86_64.exe/kitty-pane-bg-windows-x86_64.exe
        body: |
          ## Changes in this release
          
          See [CHANGELOG.md](CHANGELOG.md) for details.
          
          ## Installation
          
          ### Quick Install (Unix-like systems only - the superior choice)
          ```bash
          curl -sSL https://raw.githubusercontent.com/daringjoker/kitty-pane-bg/main/install.sh | sh
          ```
          
          ### Manual Install
          
          #### Linux/Windows
          1. Download the appropriate binary for your platform:
             - `kitty-pane-bg-linux-x86_64` for Linux x86_64
             - `kitty-pane-bg-windows-x86_64.exe` for Windows x86_64
          2. Make it executable (Linux): `chmod +x kitty-pane-bg-*`
          3. Rename and move: `mv kitty-pane-bg-* ~/.local/bin/kitty-pane-bg`
          
          #### Other Platforms (macOS, ARM)
          For other platforms like macOS or ARM-based Linux, please build from source using the installation script. The script will automatically detect that a pre-built binary is not available and compile it for you.
          
          ## Supported Platforms
          - 🐧 Linux x86_64 (The Champion)
          - 🪟 Windows x86_64 (We Don't Judge... Much)
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
